# Generated by Django 4.1.7 on 2023-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='beakLength',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finch',
            name='color',
            field=models.CharField(default='gray', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finch',
            name='species',
            field=models.CharField(default='Crimson Finch', max_length=100),
            preserve_default=False,
        ),
    ]
